name: EXPlots
version: '${project.version}'
main: poptartfrompluto.explots.EXPlots
api-version: 1.19
depend: [ Towny ]
authors: [ PoptartFromPluto ]
description: Let players trade experience for plots in Towny
commands:
  EXPlots:
    usage: /EXPlots buy
    description: Trades XP for a plot that goes to your town